### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by gumptior** [meet-one/Client-SDK-iOS#1]
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: error memo","file":"wasm_interface.cpp","line_number":917,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":72,"method":"exec_one"}]}}

**Comment by fubin0083** [comment]
你好，是在对接什么的时候发生这个错误的呐

**Comment by wuyahuang** [comment]
@LY-Coder 你这个是合约报错了。找找你的合约哪里抛出的 "error memo"提示。

**Comment by tabathap** [comment]
💴💵💶💸
