### ISSUE TITLE
error with 2.1.2 version 

### ISSUE THREAD

**Issue by AlchemistNotus** [meet-one/Client-SDK-iOS#2]
With new 2.1.2 we have error in building process:
235: error: exportArchive: Failed to verify bitcode in MODAppSDK.framework/MODAppSDK:
236: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in MODAppSDK.framework/MODAppSDK:
237: Error packaging up the application
238: [!] Error packaging up the application

2.1.1 - all are fine.

build on unity_cloud_build. add sdk with podfile

**Comment by fubin0083** [comment]
We have recompiled the 2.1.2.1 version and successfully uploaded the demo to the AppStore, you can "pod update" and try again.

Thank you.
